In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow.keras.models import Sequential, load_model
from tensorflow.keras.layers import Dense
from sklearn.metrics import accuracy_score
data = pd.read_csv("C:/Users/Abhi/Desktop/CSV files/Grade ANN.csv")
data.head()

   S1  S2  S3  S4  S5  S6  Total
0  11  18   6   5   5   3     48
1  19  13   0  15  17  19     83
2   9  11   9   6   9   8     52
3  19  13   8  11   8  12     71
4  19  13  16  17  12  10     87

In [2]:
data["Result"] = ["Pass" if Total >=80 else "Fail" for Total in data["Total"]]# We can also use 1 and 0 in place of pass-fail

In [3]:
data.head()

   S1  S2  S3  S4  S5  S6  Total Result
0  11  18   6   5   5   3     48   Fail
1  19  13   0  15  17  19     83   Pass
2   9  11   9   6   9   8     52   Fail
3  19  13   8  11   8  12     71   Fail
4  19  13  16  17  12  10     87   Pass

In [4]:
#replace target class with 0 and 1 
#1 means "Pass" and 0 means "Fail"
data['Result'] = data['Result'].replace("Fail", 0)
data['Result'] = data['Result'].replace("Pass", 1)
data.head()

   S1  S2  S3  S4  S5  S6  Total  Result
0  11  18   6   5   5   3     48       0
1  19  13   0  15  17  19     83       1
2   9  11   9   6   9   8     52       0
3  19  13   8  11   8  12     71       0
4  19  13  16  17  12  10     87       1

In [5]:
X = data.drop(columns=['Result'])
y_label = data['Result'].values.reshape(X.shape[0], 1)

In [6]:
#split data into train and test set
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
Xtrain, Xtest, ytrain, ytest = train_test_split(X, y_label, test_size=0.2, random_state=2)

In [7]:
sc = StandardScaler()
sc.fit(Xtrain)
Xtrain = sc.transform(Xtrain)
Xtest = sc.transform(Xtest)

In [8]:
model = Sequential()
model.add(Dense(units =36, activation = 'relu', input_dim=len(X.columns)))
model.add(Dense(units =72, activation = 'relu'))
model.add(Dense(units = 1, activation = 'sigmoid'))

In [9]:
model.compile(loss = 'binary_crossentropy', optimizer = 'sgd', metrics = 'accuracy')

In [10]:
model.fit(Xtrain, ytrain, epochs = 100, batch_size = 18)

Epoch 1/100
2/2 [==============================] - 0s 4ms/step - loss: 0.7273 - accuracy: 0.3929
Epoch 2/100
2/2 [==============================] - 0s 756us/step - loss: 0.7198 - accuracy: 0.4286
Epoch 3/100
2/2 [==============================] - 0s 3ms/step - loss: 0.7133 - accuracy: 0.4286
Epoch 4/100
2/2 [==============================] - 0s 0s/step - loss: 0.7066 - accuracy: 0.4286
Epoch 5/100
2/2 [==============================] - 0s 3ms/step - loss: 0.7000 - accuracy: 0.4286
Epoch 6/100
2/2 [==============================] - 0s 2ms/step - loss: 0.6936 - accuracy: 0.4643
Epoch 7/100
2/2 [==============================] - 0s 3ms/step - loss: 0.6875 - accuracy: 0.5000
Epoch 8/100
2/2 [==============================] - 0s 0s/step - loss: 0.6810 - accuracy: 0.5000
Epoch 9/100
2/2 [==============================] - 0s 1ms/step - loss: 0.6748 - accuracy: 0.5357
Epoch 10/100
2/2 [==============================] - 0s 3ms/step - loss: 0.6686 - accuracy: 0.5714
Epoch 11/100
2/2 [==============================] - 0s 2ms/step - loss: 0.6627 - accuracy: 0.5714
Epoch 12/100
2/2 [==============================] - 0s 0s/step - loss: 0.6570 - accuracy: 0.6071
Epoch 13/100
2/2 [==============================] - 0s 0s/step - loss: 0.6515 - accuracy: 0.6429
Epoch 14/100
2/2 [==============================] - 0s 1ms/step - loss: 0.6456 - accuracy: 0.6429
Epoch 15/100
2/2 [==============================] - 0s 3ms/step - loss: 0.6403 - accuracy: 0.6429
Epoch 16/100
2/2 [==============================] - 0s 0s/step - loss: 0.6350 - accuracy: 0.6786
Epoch 17/100
2/2 [==============================] - 0s 250us/step - loss: 0.6296 - accuracy: 0.6786
Epoch 18/100
2/2 [==============================] - 0s 2ms/step - loss: 0.6244 - accuracy: 0.7143
Epoch 19/100
2/2 [==============================] - 0s 4ms/step - loss: 0.6189 - accuracy: 0.7143
Epoch 20/100
2/2 [==============================] - 0s 2ms/step - loss: 0.6135 - accuracy: 0.7143
Epoch 21/100
2/2 [==============================] - 0s 3ms/step - loss: 0.6084 - accuracy: 0.7143
Epoch 22/100
2/2 [==============================] - 0s 0s/step - loss: 0.6032 - accuracy: 0.7143
Epoch 23/100
2/2 [==============================] - 0s 2ms/step - loss: 0.5979 - accuracy: 0.7143
Epoch 24/100
2/2 [==============================] - 0s 1ms/step - loss: 0.5930 - accuracy: 0.7143
Epoch 25/100
2/2 [==============================] - 0s 2ms/step - loss: 0.5881 - accuracy: 0.7500
Epoch 26/100
2/2 [==============================] - 0s 4ms/step - loss: 0.5835 - accuracy: 0.7500
Epoch 27/100
2/2 [==============================] - 0s 5ms/step - loss: 0.5786 - accuracy: 0.7857
Epoch 28/100
2/2 [==============================] - 0s 3ms/step - loss: 0.5743 - accuracy: 0.7857
Epoch 29/100
2/2 [==============================] - 0s 0s/step - loss: 0.5699 - accuracy: 0.8214
Epoch 30/100
2/2 [==============================] - 0s 2ms/step - loss: 0.5654 - accuracy: 0.8214
Epoch 31/100
2/2 [==============================] - 0s 3ms/step - loss: 0.5608 - accuracy: 0.8571
Epoch 32/100
2/2 [==============================] - 0s 248us/step - loss: 0.5565 - accuracy: 0.8571
Epoch 33/100
2/2 [==============================] - 0s 695us/step - loss: 0.5522 - accuracy: 0.8571
Epoch 34/100
2/2 [==============================] - 0s 249us/step - loss: 0.5477 - accuracy: 0.8571
Epoch 35/100
2/2 [==============================] - 0s 2ms/step - loss: 0.5434 - accuracy: 0.8571
Epoch 36/100
2/2 [==============================] - 0s 3ms/step - loss: 0.5392 - accuracy: 0.8571
Epoch 37/100
2/2 [==============================] - 0s 0s/step - loss: 0.5345 - accuracy: 0.8571
Epoch 38/100
2/2 [==============================] - 0s 2ms/step - loss: 0.5304 - accuracy: 0.8571
Epoch 39/100
2/2 [==============================] - 0s 1ms/step - loss: 0.5266 - accuracy: 0.8929
Epoch 40/100
2/2 [==============================] - 0s 3ms/step - loss: 0.5220 - accuracy: 0.8929
Epoch 41/100
2/2 [==============================] - 0s 4ms/step - loss: 0.5182 - accuracy: 0.8929
Epoch 42/100
2/2 [==============================] - 0s 3ms/step - loss: 0.5141 - accuracy: 0.8929
Epoch 43/100
2/2 [==============================] - 0s 4ms/step - loss: 0.5103 - accuracy: 0.8929
Epoch 44/100
2/2 [==============================] - 0s 3ms/step - loss: 0.5064 - accuracy: 0.8929
Epoch 45/100
2/2 [==============================] - 0s 6ms/step - loss: 0.5024 - accuracy: 0.8929
Epoch 46/100
2/2 [==============================] - 0s 3ms/step - loss: 0.4987 - accuracy: 0.8929
Epoch 47/100
2/2 [==============================] - 0s 5ms/step - loss: 0.4946 - accuracy: 0.9286
Epoch 48/100
2/2 [==============================] - 0s 2ms/step - loss: 0.4908 - accuracy: 0.9286
Epoch 49/100
2/2 [==============================] - 0s 4ms/step - loss: 0.4867 - accuracy: 0.9286
Epoch 50/100
2/2 [==============================] - 0s 229us/step - loss: 0.4831 - accuracy: 0.9286
Epoch 51/100
2/2 [==============================] - 0s 4ms/step - loss: 0.4794 - accuracy: 0.9643
Epoch 52/100
2/2 [==============================] - 0s 6ms/step - loss: 0.4758 - accuracy: 0.9643
Epoch 53/100
2/2 [==============================] - 0s 4ms/step - loss: 0.4722 - accuracy: 0.9643
Epoch 54/100
2/2 [==============================] - 0s 0s/step - loss: 0.4687 - accuracy: 0.9643
Epoch 55/100
2/2 [==============================] - 0s 3ms/step - loss: 0.4651 - accuracy: 0.9643
Epoch 56/100
2/2 [==============================] - 0s 3ms/step - loss: 0.4617 - accuracy: 0.9643
Epoch 57/100
2/2 [==============================] - 0s 4ms/step - loss: 0.4583 - accuracy: 0.9643
Epoch 58/100
2/2 [==============================] - 0s 4ms/step - loss: 0.4546 - accuracy: 0.9643
Epoch 59/100
2/2 [==============================] - 0s 0s/step - loss: 0.4512 - accuracy: 0.9643
Epoch 60/100
2/2 [==============================] - 0s 1ms/step - loss: 0.4477 - accuracy: 0.9643
Epoch 61/100
2/2 [==============================] - 0s 4ms/step - loss: 0.4444 - accuracy: 0.9643
Epoch 62/100
2/2 [==============================] - 0s 4ms/step - loss: 0.4410 - accuracy: 0.9643
Epoch 63/100
2/2 [==============================] - 0s 0s/step - loss: 0.4376 - accuracy: 0.9643
Epoch 64/100
2/2 [==============================] - 0s 3ms/step - loss: 0.4345 - accuracy: 0.9643
Epoch 65/100
2/2 [==============================] - 0s 1ms/step - loss: 0.4313 - accuracy: 0.9643
Epoch 66/100
2/2 [==============================] - 0s 0s/step - loss: 0.4284 - accuracy: 0.9643
Epoch 67/100
2/2 [==============================] - 0s 253us/step - loss: 0.4252 - accuracy: 0.9643
Epoch 68/100
2/2 [==============================] - 0s 5ms/step - loss: 0.4219 - accuracy: 0.9643
Epoch 69/100
2/2 [==============================] - 0s 4ms/step - loss: 0.4188 - accuracy: 0.9643
Epoch 70/100
2/2 [==============================] - 0s 0s/step - loss: 0.4157 - accuracy: 0.9643
Epoch 71/100
2/2 [==============================] - 0s 2ms/step - loss: 0.4126 - accuracy: 0.9643
Epoch 72/100
2/2 [==============================] - 0s 6ms/step - loss: 0.4098 - accuracy: 0.9643
Epoch 73/100
2/2 [==============================] - 0s 4ms/step - loss: 0.4067 - accuracy: 0.9643
Epoch 74/100
2/2 [==============================] - 0s 2ms/step - loss: 0.4038 - accuracy: 0.9643
Epoch 75/100
2/2 [==============================] - 0s 4ms/step - loss: 0.4009 - accuracy: 0.9643
Epoch 76/100
2/2 [==============================] - 0s 6ms/step - loss: 0.3979 - accuracy: 0.9643
Epoch 77/100
2/2 [==============================] - 0s 3ms/step - loss: 0.3950 - accuracy: 0.9643
Epoch 78/100
2/2 [==============================] - 0s 0s/step - loss: 0.3924 - accuracy: 0.9643
Epoch 79/100
2/2 [==============================] - 0s 4ms/step - loss: 0.3895 - accuracy: 0.9643
Epoch 80/100
2/2 [==============================] - 0s 0s/step - loss: 0.3866 - accuracy: 0.9643
Epoch 81/100
2/2 [==============================] - 0s 4ms/step - loss: 0.3837 - accuracy: 0.9643
Epoch 82/100
2/2 [==============================] - 0s 0s/step - loss: 0.3810 - accuracy: 0.9643
Epoch 83/100
2/2 [==============================] - 0s 3ms/step - loss: 0.3785 - accuracy: 0.9643
Epoch 84/100

2/2 [==============================] - 0s 6ms/step - loss: 0.3758 - accuracy: 0.9643
Epoch 85/100
2/2 [==============================] - 0s 4ms/step - loss: 0.3732 - accuracy: 0.9643
Epoch 86/100
2/2 [==============================] - 0s 3ms/step - loss: 0.3705 - accuracy: 0.9643
Epoch 87/100
2/2 [==============================] - 0s 2ms/step - loss: 0.3679 - accuracy: 0.9643
Epoch 88/100
2/2 [==============================] - 0s 1ms/step - loss: 0.3656 - accuracy: 0.9643
Epoch 89/100
2/2 [==============================] - 0s 2ms/step - loss: 0.3629 - accuracy: 0.9643
Epoch 90/100
2/2 [==============================] - 0s 3ms/step - loss: 0.3604 - accuracy: 0.9643
Epoch 91/100
2/2 [==============================] - 0s 0s/step - loss: 0.3580 - accuracy: 0.9643
Epoch 92/100
2/2 [==============================] - 0s 2ms/step - loss: 0.3555 - accuracy: 0.9643
Epoch 93/100
2/2 [==============================] - 0s 5ms/step - loss: 0.3530 - accuracy: 0.9643
Epoch 94/100
2/2 [==============================] - 0s 0s/step - loss: 0.3506 - accuracy: 0.9643
Epoch 95/100
2/2 [==============================] - 0s 0s/step - loss: 0.3484 - accuracy: 0.9643
Epoch 96/100
2/2 [==============================] - 0s 1ms/step - loss: 0.3457 - accuracy: 0.9643
Epoch 97/100
2/2 [==============================] - 0s 4ms/step - loss: 0.3434 - accuracy: 0.9643
Epoch 98/100
2/2 [==============================] - 0s 3ms/step - loss: 0.3411 - accuracy: 0.9643
Epoch 99/100
2/2 [==============================] - 0s 2ms/step - loss: 0.3388 - accuracy: 0.9643
Epoch 100/100
2/2 [==============================] - 0s 486us/step - loss: 0.3366 - accuracy: 0.9643

In [11]:
y_hat = model.predict(Xtest)
y_hat = [0 if val<0.5 else 1 for val in y_hat]

In [12]:
accuracy_score(ytest, y_hat)

1.0